# Generated by Django 4.2.11 on 2024-03-30 06:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('propnumber', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('OwnerName', models.CharField(max_length=120)),
                ('Village', models.CharField(max_length=120)),
                ('District', models.CharField(blank=True, max_length=120, null=True)),
                ('Taluk', models.CharField(blank=True, max_length=120, null=True)),
                ('City', models.CharField(max_length=120)),
                ('State', models.CharField(max_length=120)),
                ('Location', models.CharField(max_length=120)),
                ('Size', models.CharField(choices=[('acres', 'Acres'), ('sqft', 'Sq.ft'), ('cents', 'Cents')], max_length=120)),
                ('Bookvalue', models.CharField(max_length=120)),
                ('guidelinevalue', models.CharField(max_length=120)),
                ('mortagage', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=120)),
                ('assetcategory', models.CharField(choices=[('land', 'Land'), ('leasehold', 'Lease hold land'), ('building', 'Building'), ('landbuilding', 'Land and Building'), ('factory', 'Factory Building'), ('agriland', 'Agricultural Land'), ('commercial', 'Commercial Building'), ('resident', 'Residential Building'), ('other', 'Other Asset')], max_length=120)),
                ('approvedplan', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=120)),
                ('registrationdate', models.DateField(default=datetime.date.today)),
                ('disposaldate', models.DateField(default=datetime.date.today)),
                ('documentloc', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'property',
            },
        ),
        migrations.CreateModel(
            name='propertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Saledeed', models.FileField(blank=True, max_length=1000, null=True, upload_to='documents/')),
                ('Patta', models.FileField(blank=True, max_length=1000, null=True, upload_to='documents/')),
                ('Taxpayments', models.FileField(blank=True, max_length=1000, null=True, upload_to='documents/')),
                ('Fieldmeasurement', models.FileField(blank=True, max_length=1000, null=True, upload_to='documents/')),
                ('Adangal', models.FileField(blank=True, max_length=1000, null=True, upload_to='documents/')),
                ('Encumbrance', models.FileField(blank=True, max_length=1000, null=True, upload_to='documents/')),
                ('Approvals', models.FileField(blank=True, max_length=1000, null=True, upload_to='documents/')),
                ('EB', models.FileField(blank=True, max_length=1000, null=True, upload_to='documents/')),
                ('Parent', models.FileField(blank=True, max_length=1000, null=True, upload_to='documents/')),
                ('Legal', models.FileField(blank=True, max_length=1000, null=True, upload_to='documents/')),
                ('Mortgage', models.FileField(blank=True, max_length=1000, null=True, upload_to='documents/')),
                ('Poweratorny', models.FileField(blank=True, max_length=1000, null=True, upload_to='documents/')),
                ('FormRegister', models.FileField(blank=True, max_length=1000, null=True, upload_to='documents/')),
                ('Revenue', models.FileField(blank=True, max_length=1000, null=True, upload_to='documents/')),
                ('Miscellaneous', models.FileField(blank=True, max_length=1000, null=True, upload_to='documents/')),
                ('propnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.property')),
            ],
            options={
                'db_table': 'document',
            },
        ),
    ]
